// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: export.proto

package io.greptime.export;

/**
 * Protobuf enum {@code CompressionType}
 */
public enum CompressionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>Zstd = 0;</code>
   */
  Zstd(0),
  /**
   * <code>Deflate = 1;</code>
   */
  Deflate(1),
  /**
   * <code>Bz = 2;</code>
   */
  Bz(2),
  /**
   * <code>Lzma = 3;</code>
   */
  Lzma(3),
  /**
   * <code>Xz = 4;</code>
   */
  Xz(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>Zstd = 0;</code>
   */
  public static final int Zstd_VALUE = 0;
  /**
   * <code>Deflate = 1;</code>
   */
  public static final int Deflate_VALUE = 1;
  /**
   * <code>Bz = 2;</code>
   */
  public static final int Bz_VALUE = 2;
  /**
   * <code>Lzma = 3;</code>
   */
  public static final int Lzma_VALUE = 3;
  /**
   * <code>Xz = 4;</code>
   */
  public static final int Xz_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CompressionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static CompressionType forNumber(int value) {
    switch (value) {
      case 0: return Zstd;
      case 1: return Deflate;
      case 2: return Bz;
      case 3: return Lzma;
      case 4: return Xz;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CompressionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CompressionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CompressionType>() {
          public CompressionType findValueByNumber(int number) {
            return CompressionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.greptime.export.Export.getDescriptor().getEnumTypes().get(0);
  }

  private static final CompressionType[] VALUES = values();

  public static CompressionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CompressionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:CompressionType)
}

