// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: export.proto

package io.greptime.export;

public interface DataExportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataExportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 sst_count = 1;</code>
   * @return The sstCount.
   */
  int getSstCount();
}
