// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: export.proto

package io.greptime.export;

public final class Export {
  private Export() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataExportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataExportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataExportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataExportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014export.proto\"\217\003\n\021DataExportRequest\022\017\n\007" +
      "catalog\030\001 \001(\t\022\016\n\006schema\030\002 \001(\t\022\016\n\006tables\030" +
      "\003 \003(\t\022\021\n\tfile_path\030\004 \001(\t\022\021\n\tfile_name\030\005 " +
      "\001(\t\022\035\n\020min_timestamp_ms\030\006 \001(\003H\000\210\001\001\022\035\n\020ma" +
      "x_timestamp_ms\030\007 \001(\003H\001\210\001\001\022*\n\020compression" +
      "_type\030\010 \001(\0162\020.CompressionType\022\031\n\021compres" +
      "sion_level\030\t \001(\005\022\037\n\027compression_interval" +
      "_ms\030\n \001(\004\022\035\n\025bytes_per_compression\030\013 \001(\004" +
      "\022\024\n\007task_id\030\014 \001(\tH\002\210\001\001\022\022\n\nblack_list\030\r \003" +
      "(\tB\023\n\021_min_timestamp_msB\023\n\021_max_timestam" +
      "p_msB\n\n\010_task_id\"\'\n\022DataExportResponse\022\021" +
      "\n\tsst_count\030\001 \001(\r*B\n\017CompressionType\022\010\n\004" +
      "Zstd\020\000\022\013\n\007Deflate\020\001\022\006\n\002Bz\020\002\022\010\n\004Lzma\020\003\022\006\n" +
      "\002Xz\020\0042C\n\nDataExport\0225\n\nDataExport\022\022.Data" +
      "ExportRequest\032\023.DataExportResponseB\026\n\022io" +
      ".greptime.exportP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DataExportRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DataExportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataExportRequest_descriptor,
        new java.lang.String[] { "Catalog", "Schema", "Tables", "FilePath", "FileName", "MinTimestampMs", "MaxTimestampMs", "CompressionType", "CompressionLevel", "CompressionIntervalMs", "BytesPerCompression", "TaskId", "BlackList", "MinTimestampMs", "MaxTimestampMs", "TaskId", });
    internal_static_DataExportResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataExportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataExportResponse_descriptor,
        new java.lang.String[] { "SstCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
